CREATE TABLE usuarios_pf(idUsuario INT PRIMARY KEY AUTO_INCREMENT NOT NULL, nombre VARCHAR(255) NOT NULL, correo VARCHAR(255) NOT NULL, contrasenia VARCHAR(255) NOT NULL, tipo ENUM ('u','a') DEFAULT 'u' NOT NULL);

CREATE TABLE eventos_pf(idEvento INT PRIMARY KEY AUTO_INCREMENT NOT NULL, nombre VARCHAR(255) NOT NULL, fechaInicio DATE NOT NULL, fechaFinal DATE NOT NULL, ubicacion VARCHAR(512) NOT NULL, descripcion VARCHAR(512) NOT NULL);

CREATE TABLE actividades_pf(idActividad INT PRIMARY KEY AUTO_INCREMENT NOT NULL, idEvento INT NOT NULL, CONSTRAINT idEvento_fk FOREIGN KEY(idEvento) REFERENCES eventos_pf(idEvento) ON DELETE CASCADE ON UPDATE CASCADE, nombre VARCHAR(255) NOT NULL, hora TIME NOT NULL, fecha DATE NOT NULL, sala INT NOT NULL);

CREATE TABLE presentadores_pf(idPresentador INT PRIMARY KEY AUTO_INCREMENT NOT NULL, nombre VARCHAR(255) NOT NULL, especializacion VARCHAR(255) NOT NULL, ocupacion VARCHAR(255) NOT NULL);

CREATE TABLE inscripciones_pf(idInscripcion INT PRIMARY KEY AUTO_INCREMENT NOT NULL, idUsuario INT NOT NULL, CONSTRAINT idUsuario_fk FOREIGN KEY(idUsuario) REFERENCES usuarios_pf(idUsuario) ON DELETE CASCADE ON UPDATE CASCADE, idEvento INT NOT NULL, CONSTRAINT idEvento_fk2 FOREIGN KEY(idEvento) REFERENCES eventos_pf(idEvento) ON DELETE CASCADE ON UPDATE CASCADE, fechaInscripcion DATE NOT NULL);

CREATE TABLE asistencias_pf(idAsistencia INT PRIMARY KEY AUTO_INCREMENT NOT NULL, idUsuario INT NOT NULL, CONSTRAINT idUsuario_fk2 FOREIGN KEY(idUsuario) REFERENCES usuarios_pf(idUsuario) ON DELETE CASCADE ON UPDATE CASCADE, idActividad INT NOT NULL, CONSTRAINT idActividad_fk2 FOREIGN KEY(idActividad) REFERENCES actividades_pf(idActividad) ON DELETE CASCADE ON UPDATE CASCADE, fechaAsistencia DATE NOT NULL);

CREATE TABLE actividades_presentadores_pf(idActividad INT NOT NULL, CONSTRAINT idActividad_fk3 FOREIGN KEY(idActividad) REFERENCES actividades_pf(idActividad) ON DELETE CASCADE ON UPDATE CASCADE, idPresentador INT NOT NULL, CONSTRAINT idPresentador_fk2 FOREIGN KEY(idPresentador) REFERENCES presentadores_pf(idPresentador) ON DELETE CASCADE ON UPDATE CASCADE);

CREATE TABLE asistentes_pf(idAsistente INT PRIMARY KEY, CONSTRAINT idAsistente_fk FOREIGN KEY (idAsistente) REFERENCES usuarios_pf(idUsuario) ON DELETE CASCADE ON UPDATE CASCADE, matricula VARCHAR(20) UNIQUE NOT NULL, carrera VARCHAR(100) NOT NULL); 